### ISSUE TITLE
Gitter vs Telegram

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipylatam-webpage-2019#3]
I noticed that someone created https://gitter.im/scipy-latinamerica/lobby. We already have a Telegram group.

I believe that use two chat platforms doesn't help communication!

**Comment by goanpeca** [comment]
It was me (Co organizing SciPy Latam) @rgaiacs and the use of Gitter is for embedding a liv chat on the website, which gitter makes a breeze and telegram does not.

**Comment by rgaiacs** [comment]
> the use of Gitter is for embedding a live chat on the website

I think that a "Join our chat" button would be fine. You don't need a embedded chat.

> they serve different purposes and different niches

Is a "versus" issue because you are requiring some users to have two accounts / two apps / two websites.

> and everyone is free to use what they consider necessary.

Organisers and attendees are free to use what they want: WhatsApp, Telegram, Signal, Gitter, Slack, IRC, Matrix/Riot, ...

The point that I'm raising is that if the SciPy Latin America **group** is trying to build a community they should consider avoid too many **official** channels because it requires extra work (e.g. if the group has official WhatsApp, Telegram and Gitter chat, the group have 3 places to send official announcements). I consider that offering RSS/Atom, email notification subscription and one chat (to rule them all) is already good enough. If someone uses another chat system and want notification on it they can use the RSS/Atom but the **group** doesn't need to maintain infrastructure.

> In Colombia (where the conference is taking place), telegram is not used nearly as much as it is in Brazil or Argentina, so it is easier to embed a chat on a website for questions regarding conference inquiries.

As I mentioned before, I think that a "Join our chat" button is enough. I would buy the idea of using Gitter if the reasoning was "Telegram doesn't have a web version" (they have https://web.telegram.org) or "Telegram requires to have an app running on your smart phone" (this is the case of WhatsApp). But the embedded is too weak to me.

> I feel the gitter chat is for the conference related issues whereas the telegram seems to be the Latin-American community for Scientific computing in Python, and not necessarily the conference per se.

You could create one Telegram chat specific for the conference.

Another thing is that we try to use Gitter back in 2016. @xmnlab @ocefpaf @melissawm and others mentioned that the Gitter app on their smart-phone was not sending notifications after some time. I don't know if this was fixed.

**Comment by ocefpaf** [comment]
> Another thing is that we try to use Gitter back in 2016. @xmnlab @ocefpaf @melissawm and others mentioned that the Gitter app on their smart-phone was not sending notifications after some time. I don't know if this was fixed.

While I don't have a strong preference on gitter vs telegram I do prefer a single channel for communication. I'm already completely lost in the multiple telegram channels and it is highly unlikely that I will be able to follow anything on gitter.

> they serve different purposes and different niches, and everyone is free to use what they consider necessary

Not really. If one wants to participate in the discussion they have to use them all  or be left out. And the feeling of being left out is terrible for community building.

It would be a niche if the scope of the gitter channel is reduced to website problems, or something like it. However, it does look like it based on the title of the chat: "SciPy Latin america Colombia Conference Chat / Chat de la conferencia SciPy Latam," that is quite broad context!

I agree with @rgaiacs, a single channel helps build a stronger community.

Again, I don't really a stake on this. I cannot cope with that many communication channels (and messages!) so I'm "out" anyway. But, if SciPyLA strives to be an inclusive community, we should start worrying about making communications/messaging more accessible, readable, and meaningful to all.

**Comment by goanpeca** [comment]
Thanks for the feedback, now...

- There is at the moment no official channel for conference related issues. Creating a telegram room just for that does not cut it for the use case (see next point). Having 2 telegram rooms with one saying conference and the other saying group really makes it even more confusing. Telegram, unfortunately, does not have the concept of sub rooms or channels within a room so you have to create more and more channels for specific topics which do not really scale well (for usage)
- Gitter allows for login with Twitter or Github directly from the conference website (in case the user does not have an account already), so no need to look at a smartphone for a code. Not all attendees are programmers and even if they are it is more likely they will have a github or a twitter account that a telegram one. Keep in mind this is the case for Colombia, where the main bulk of the conference audience is coming from.
- `"SciPy Latin america Colombia Conference Chat / Chat de la conferencia SciPy Latam," that is quite broad context!` Regarding this I can make the scope much narrower.

>While I don't have a strong preference on gitter vs telegram I do prefer a single channel for communication. I'm already completely lost in the multiple telegram channels and it is highly unlikely that I will be able to follow anything on gitter.

- As stated before this is for the conference as a quick access for questions regarding tickets not for the broader community. I took the liberty of adding all you guys to the gitter chat, but you are free to ignore it since no community issues will be discussed there.

>As I mentioned before, I think that a "Join our chat" button is enough. I would buy the idea of using Gitter if the reasoning was "Telegram doesn't have a web version" (they have https://web.telegram.org) or "Telegram requires to have an app running on your smart phone" (this is the case of WhatsApp). But the embedded is too weak to me.

Well that is your opinion, and I appreciate you share it, but this is really not making things easier for the conference attendees which is the goal.

**Comment by goanpeca** [comment]
>But, if SciPyLA strives to be an inclusive community, we should start worrying about making communications/messaging more accessible, readable, and meaningful to all.

This is probably a broader discussion, but now that is mentioned having a single channel for communication does not make the community inclusive.

- Does it make the life of the leaders of the community easier? Probably, but that is a weak point for wanting to have a bigger more diverse community.

In Colombia (Python Colombia) we took a different approach: For internal meetings and group organization, we use slack, which is not really open and requires an explicit invitation. And for the rest we try to have different channels, telegram (which was not being used a year ago...), twitter, instagram, facebook, facebook groups, whatsapp... etc. Does this make it harder for us organizers? a little bit (not that much really...) but now we are reaching a broader audience.

**Comment by xmnlab** [comment]
I think we need to keep in mind that one goal of the conference is make the community grow ... and the community is centered in telegram now ... so use gitter the attend will need to install gitter for the conference and after the conference telegram ... so not sure if it is a good workflow. 

About our  experience in Brazil I can say we used a lot the channel ... for announcement during the event and also the social events ... 

so I know you in Colombia have the last words about that .. but keep in mind to make efforts to help the community grow up ... in each country the popular chat app could be anything ... but we are centering all the communication on telegram and for the oldest members use replicate the messages on google group.

**Comment by xmnlab** [comment]
in another words we ask you all to promote our telegram group anyway ... if you also want to use gitter is your decision .. but please promote our telegram group

**Comment by goanpeca** [comment]
>so I know you in Colombia have the last words about that .. but keep in mind to make efforts to help the community grow up ... in each country the popular chat app could be anything ... but we are centering all the communication on telegram and for the oldest members use replicate the messages on google group.

This is clear @xmnlab that is why I said that this is a conference thing not a group/community thing. The website will have the "Live chat" much like  https://2018.pycon.co/

But the bottom will include all the community links, which will include the telegram group.
